# Generated by Django 4.1.5 on 2023-02-14 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('depId', models.AutoField(primary_key=True, serialize=False)),
                ('depName', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('empId', models.AutoField(primary_key=True, serialize=False)),
                ('empName', models.CharField(max_length=10)),
                ('depName', models.CharField(max_length=10)),
                ('joiningDate', models.DateField()),
                ('photoName', models.CharField(max_length=500)),
            ],
        ),
    ]
